"""Criando campo senha na tabela comments

Revision ID: 8e7770ede790
Revises: 5e6ba8806d7e
Create Date: 2026-02-16 01:02:29.897056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7770ede790'
down_revision: Union[str, Sequence[str], None] = '5e6ba8806d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('senha', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'senha')
    # ### end Alembic commands ###
